// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIK1cjzVTn4nT9R_1LGztUtM9uqv1IM34',
    appId: '1:845051045227:web:7bc813092d2b18319e982e',
    messagingSenderId: '845051045227',
    projectId: 'fingerfarm',
    authDomain: 'fingerfarm.firebaseapp.com',
    databaseURL: 'https://fingerfarm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fingerfarm.appspot.com',
    measurementId: 'G-K2Q2V300KJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGRckwb9AFO25dbmLWK-NOPXSY2eX9to',
    appId: '1:845051045227:android:3f9803b9b469a2449e982e',
    messagingSenderId: '845051045227',
    projectId: 'fingerfarm',
    databaseURL: 'https://fingerfarm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fingerfarm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfeTS1ws-ELBa2dqUFidhPOy_Tt--Okhw',
    appId: '1:845051045227:ios:7a6cbf8cea9d8d4b9e982e',
    messagingSenderId: '845051045227',
    projectId: 'fingerfarm',
    databaseURL: 'https://fingerfarm-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fingerfarm.appspot.com',
    iosBundleId: 'com.example.fingerFarm',
  );

}